### PR TITLE
Hover on note to delete (#10)

### LINKED ISSUE #10: Delete button should be hidden until you hover on the card
I'd recommend having the delete button hidden until you hover on the card

_Originally posted by @ethanelliott in https://github.com/andy-ta/retrospective/issues/8#issuecomment-908307492_

### PR DESCRIPTION
**Pull request by andy-ta**
Changed button for folded corner. Closes #10.

### CODE REVIEW

**Comment by andy-ta** [comment]
image

**Comment by RiadGahlouz** [comment]
This looks like a UI for creating a new note or extending the current note, not removing it. The 2 UX indicators of removal I can think about are the color red and a deletion icon (Garbage bin, X, etc.)

**Comment by andy-ta** [comment]
> This looks like a UI for creating a new note or extending the current note, not removing it. The 2 UX indicators of removal I can think about are the color red and a deletion icon (Garbage bin, X, etc.)

I wanted to try like a "peeling off a sticky note" feeling rather than the usual deletion icon. Thoughts?

**Comment by ethanelliott** [comment]
Does the corner fold in when you hover?

If it "folds" over it could still show a trashcan icon on it in red

**Comment by andy-ta** [comment]
> Does the corner fold in when you hover?
> 
> If it "folds" over it could still show a trashcan icon on it in red

There's no transition animation, but it starts off as the full sticky note, and on hover it suddenly appears "folded". You are suggesting that we can put the symbol in the darker-shaded folding?

**Comment by RiadGahlouz** [comment]
> > Does the corner fold in when you hover?
> > If it "folds" over it could still show a trashcan icon on it in red
> 
> There's no transition animation, but it starts off as the full sticky note, and on hover it suddenly appears "folded". You are suggesting that we can put the symbol in the darker-shaded folding?

Yeah we could do a little animation to simulate the peeling, we could put an icon there then to make it obvious it's going to delete the note

**Pull request closed without merging**
